name: "rust-releaser"
description: Release a Rust project to a personal homebrew tap.

inputs:
    executable:
        description: the name of the tool when installed
        required: true
    refname:
        description: the refname for the release being created
        required: true
    tap_repo:
        description: the tap repo, specified in owner/repo form
        required: true
        default: "ceejbot/homebrew-tap"
    tap_email:
        description: the email to use for the commit into the tap repo
        required: true
        default: "ceejceej@gmail.com"
    tap_user:
        description: the user name to use for the commit into the tap repo
        required: true
        default: "formula robot"
    tap_token:
        description: a gh token with write access to the homebrew tap repo
        required: true

runs:
    using: composite
    steps:
        - name: check out the repo
          uses: actions/checkout@v4

        - name: get stable + nightly Rust
          uses: actions-rust-lang/setup-rust-toolchain@v1
          with:
              toolchain: nightly, stable
              components: clippy, rustfmt
              target: aarch64-apple-darwin, x86_64-apple-darwin
              cache-directories: |
                  ~/.cargo/registry
                  ~/.cargo/bin
                  target

        - name: get cargo-nextest on path
          shell: bash
          run: |
              if [[ -z $(which cargo-nextest) ]]; then
                curl -sL https://get.nexte.st/latest/mac -o nextest.tgz
                tar xfz nextest.tgz
                mv cargo-nextest ~/.cargo/bin
                rm nextest.tgz
              fi

        - name: run the tests
          shell: bash
          run: cargo +stable nextest run --no-tests warn

        - name: consult Clippy
          shell: bash
          run: cargo +stable clippy --all-targets

        - name: check formatting
          shell: bash
          run: cargo +nightly fmt --check --all

        - name: get formulaic on path
          shell: bash
          env:
              GH_TOKEN: ${{ env.REPO_TOKEN }}
          run: |
              if [[ -z $(which formulaic) ]]; then
                  gh release download --repo ceejbot/formulaic --pattern \*aarch64-apple-darwin.tar.gz -O formulaic.tgz
                  tar xfz formulaic.tgz
                  mv formulaic ~/.cargo/bin
                  rm formulaic.tgz
              fi

        - name: create github release
          shell: bash
          env:
              REFNAME: ${{ inputs.refname }}
              GH_TOKEN: ${{ env.REPO_TOKEN }}
          run: gh release create "$REFNAME" --generate-notes

        - name: create and upload release assets
          env:
              GH_TOKEN: ${{ env.REPO_TOKEN }}
              GITHUB_ACCESS_TOKEN: ${{ env.REPO_TOKEN}}
              EXECUTABLE: ${{ inputs.executable }}
              REFNAME: ${{ inputs.refname }}
          shell: bash
          run: |
              mkdir -p dist
              cd dist
              for target in "aarch64-apple-darwin" "x86_64-apple-darwin"; do
                  cargo +stable build --release --target $target

                  tar czf $EXECUTABLE-$target.tar.gz --strip-components=4  ../target/$target/release/$EXECUTABLE
                  gh release upload "$REFNAME" "$EXECUTABLE-$target.tar.gz"

                  digest=$(shasum -a 256 $EXECUTABLE-$target.tar.gz)
                  shasum=$(echo $digest | { read first rest; echo $first; } )
                  echo $shasum > $EXECUTABLE-"$target".tar.gz.sha256
                  gh release upload "$REFNAME" "$EXECUTABLE-$target.tar.gz.sha256"
              done
              formula_file=$(formulaic ../Cargo.toml)

        - name: update the homebrew tap
          env:
              EXECUTABLE: ${{ inputs.executable }}
              REFNAME: ${{ inputs.refname }}
              TAP_REPO: ${{ inputs.tap_repo }}
              TAP_USER: ${{ inputs.tap_user }}
              GH_TOKEN: ${{ env.HOMEBREW_TAP_TOKEN }}
          shell: bash
          run: |
              gh repo clone $TAP_REPO
              cd ${TAP_REPO##*/} || exit 1
              cp ../$EXECUTABLE.rb Formula/
              git add Formula/$EXECUTABLE.rb
              git config user.name "$TAP_REPO"
              git config user.email "$TAP_USER"
              git commit -m "$EXECUTABLE $REFNAME"
              git push https://x-access-token:$GH_TOKEN@github.com/$TAP_REPO.git
